# Digite um numero interio e veja sua tabuada
import time
numero = int(input("digite um número: "))
time.sleep(1)
print(numero * 1)
time.sleep(1)
print(numero * 2)
time.sleep(1)
print(numero * 3)
time.sleep(1)
print(numero * 4)
time.sleep(1)
print(numero * 5)
time.sleep(1)
print(numero * 6)
time.sleep(1)
print(numero * 7)
time.sleep(1)
print(numero * 8)
time.sleep(1)
print(numero * 9)
time.sleep(1)
print(numero * 10)